spring:
  application :
    name : Service1
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZones: http://localhost:8761/eureka
